-- SQL PLUS
-- 시스템 계정 생성
CREATE USER C##MAPERS IDENTIFIED BY mapers1234;

-- 권한 부여
GRANT dba TO C##MAPERS;

-- 테이블 생성
CREATE TABLE ACCOUNT(
	USERID VARCHAR2(50) PRIMARY KEY,
	LISENCEKEY VARCHAR2(16) NOT NULL,
	PASSWORD VARCHAR2(50) NOT NULL,
	USERMAIL VARCHAR2(50) NOT NULL,
	BIRTH VARCHAR2(15) NOT NULL,
	ADMINS INT DEFAULT 0 NOT NULL,
	IMAGES BLOB
);

CREATE TABLE BOOK(
	BOOKNUM NUMBER PRIMARY KEY,
	USERID VARCHAR2(50) NOT NULL,
	PLACE VARCHAR2(100) NOT NULL,
	BOOKDATE VARCHAR2(15) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	BLOCKS INT DEFAULT 0 NOT NULL,
	RATE INT DEFAULT 5 NOT NULL,
	IMAGES BLOB NOT NULL,
	VISITCOUNT INT DEFAULT 0 NOT NULL,
	LIKESCOUNT INT DEFAULT 0 NOT NULL,
	REPORTCOUNT INT DEFAULT 0 NOT NULL,
	CONSTRAINT FOREIGN KEY(USERID) REFERENCES ACCOUNT(USERID)
);

CREATE TABLE NOTICE(
	NOTICENUM NUMBER PRIMARY KEY,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(1000) NOT NULL,
	VISITCOUNT INT DEFAULT 0 NOT NULL
);

CREATE TABLE PAGE(
	PAGENUM NUMBER PRIMARY KEY,
	BOOKNUM NUMBER NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(1000) NOT NULL,
	IMAGES BLOB NOT NULL,
	PAGEDATE VARCHAR2(15) DEFAULT TO_CHAR(SYSDATE, 'YYYY/MM/DD') NOT NULL,
	RATE INT DEFAULT 5 NOT NULL,
	CONSTRAINT FOREIGN KEY(BOOKNUM) REFERENCES BOOK(BOOKNUM)
);

CREATE TABLE PAGEVIEW(
	NUMS NUMBER PRIMARY KEY,
	BOOKNUM NUMBER NOT NULL,
	PAGENUM INT NOT NULL,
	USERID VARCHAR2(50) NOT NULL,
	OLDPAGE INT DEFAULT 0 NOT NULL,
	NEWPAGE INT DEFAULT 0 NOT NULL,
	LIKEON INT DEFAULT 0 NOT NULL,
	CONSTRAINT FOREIGN KEY(BOOKNUM) REFERENCES BOOK(BOOKNUM),
	CONSTRAINT FOREIGN KEY(PAGENUM) REFERENCES PAGE(PAGENUM),
	CONSTRAINT FOREIGN KEY(USERID) REFERENCES ACCOUNT(USERID)
);

-- 시퀀스 생성
CREATE SEQUENCE C##MAPERS.BOOK_SEQ
	INCREMENT BY 1
	START WITH 1
	MINVALUE 1
	NOMAXVALUE
	NOCACHE
	NOCYCLE
	NOORDER;
	
CREATE SEQUENCE C##MAPERS.NOTICE_SEQ
	INCREMENT BY 1
	START WITH 1
	MINVALUE 1
	NOMAXVALUE
	NOCACHE
	NOCYCLE
	NOORDER;
	
CREATE SEQUENCE C##MAPERS.PAGE_SEQ
	INCREMENT BY 1
	START WITH 1
	MINVALUE 1
	NOMAXVALUE
	NOCACHE
	NOCYCLE
	NOORDER;

-- 커밋
COMMIT;