<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<select name="country" style="width: 70%; padding-left: 20px;">
	<option selected></option>
	<option>그리스</option>
	<option>네덜란드</option>
	<option>노르웨이</option>
	<option>뉴질랜드</option>
	<option>대만</option>
	<option>대한민국</option>
	<option>덴마크</option>
	<option>독일</option>
	<option>라트비아</option>
	<option>루마니아</option>
	<option>룩셈부르크</option>
	<option>리투아니아</option>
	<option>리히텐슈타인</option>
	<option>말레이시아</option>
	<option>멕시코</option>
	<option>몰디브</option>
	<option>몰타</option>
	<option>미국</option>
	<option>벨기에</option>
	<option>스웨덴</option>
	<option>스위스</option>
	<option>스페인</option>
	<option>슬로바키아</option>
	<option>슬로베니아</option>
	<option>싱가포르</option>
	<option>아랍에미리트(UAE)</option>
	<option>아이슬란드</option>
	<option>아일랜드</option>
	<option>에스토니아</option>
	<option>영국(UK)</option>
	<option>오스트리아</option>
	<option>이스라엘</option>
	<option>이탈리아</option>
	<option>인도네시아</option>
	<option>일본</option>
	<option>중국</option>
	<option>체코 공화국</option>
	<option>카타르</option>
	<option>캐나다</option>
	<option>태국</option>
	<option>터키</option>
	<option>포르투갈</option>
	<option>폴란드</option>
	<option>프랑스</option>
	<option>핀란드</option>
	<option>헝가리</option>
	<option>호주</option>
</select>